apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: che-operator-service-cert
  labels:
    app.kubernetes.io/component: che-operator
    app.kubernetes.io/instance: che
    app.kubernetes.io/name: che
    app.kubernetes.io/part-of: che.eclipse.org
  name: che-operator-service
  namespace: eclipse-che
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    app: che-operator
