// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/controller/che/oauth_initial_htpasswd_provider.go

// Package mock_che is a generated GoMock package.
package mock_che

import (
	gomock "github.com/golang/mock/gomock"
	v1 "github.com/openshift/api/config/v1"
	reflect "reflect"
)

// MockOpenShiftOAuthUserHandler is a mock of OpenShiftOAuthUserHandler interface
type MockOpenShiftOAuthUserHandler struct {
	ctrl     *gomock.Controller
	recorder *MockOpenShiftOAuthUserHandlerMockRecorder
}

// MockOpenShiftOAuthUserHandlerMockRecorder is the mock recorder for MockOpenShiftOAuthUserHandler
type MockOpenShiftOAuthUserHandlerMockRecorder struct {
	mock *MockOpenShiftOAuthUserHandler
}

// NewMockOpenShiftOAuthUserHandler creates a new mock instance
func NewMockOpenShiftOAuthUserHandler(ctrl *gomock.Controller) *MockOpenShiftOAuthUserHandler {
	mock := &MockOpenShiftOAuthUserHandler{ctrl: ctrl}
	mock.recorder = &MockOpenShiftOAuthUserHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockOpenShiftOAuthUserHandler) EXPECT() *MockOpenShiftOAuthUserHandlerMockRecorder {
	return m.recorder
}

// CreateOAuthInitialUser mocks base method
func (m *MockOpenShiftOAuthUserHandler) CreateOAuthInitialUser(crNamespace string, openshiftOAuth *v1.OAuth) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOAuthInitialUser", crNamespace, openshiftOAuth)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOAuthInitialUser indicates an expected call of CreateOAuthInitialUser
func (mr *MockOpenShiftOAuthUserHandlerMockRecorder) CreateOAuthInitialUser(crNamespace, openshiftOAuth interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOAuthInitialUser", reflect.TypeOf((*MockOpenShiftOAuthUserHandler)(nil).CreateOAuthInitialUser), crNamespace, openshiftOAuth)
}

// DeleteOAuthInitialUser mocks base method
func (m *MockOpenShiftOAuthUserHandler) DeleteOAuthInitialUser(crNamespace string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOAuthInitialUser", crNamespace)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOAuthInitialUser indicates an expected call of DeleteOAuthInitialUser
func (mr *MockOpenShiftOAuthUserHandlerMockRecorder) DeleteOAuthInitialUser(crNamespace interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOAuthInitialUser", reflect.TypeOf((*MockOpenShiftOAuthUserHandler)(nil).DeleteOAuthInitialUser), crNamespace)
}
