#
# Copyright (c) 2012-2018 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Red Hat, Inc. - initial API and implementation
# Force dep to vendor the code generators, which aren't imported just used at dev time.
required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/openapi-gen",
  "k8s.io/gengo/args",
]

[[override]]
  name = "k8s.io/code-generator"
  # revision for tag "kubernetes-1.12.3"
  revision = "3dcf91f64f638563e5106f21f50c31fa361c918d"

[[override]]
  name = "k8s.io/api"
  # revision for tag "kubernetes-1.12.3"
  revision = "b503174bad5991eb66f18247f52e41c3258f6348"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  # revision for tag "kubernetes-1.12.3"
  revision = "0cd23ebeb6882bd1cdc2cb15fc7b2d72e8a86a5b"

[[constraint]]
  name = "github.com/openshift/api"
  branch = "release-4.2"

[[override]]
  name = "k8s.io/apimachinery"
  # revision for tag "kubernetes-1.12.3"
  revision = "eddba98df674a16931d2d4ba75edc3a389bf633a"

[[override]]
  name = "k8s.io/client-go"
  # revision for tag "kubernetes-1.12.3"
  revision = "d082d5923d3cc0bfbb066ee5fbdea3d0ca79acf8"

[[override]]
  name = "sigs.k8s.io/controller-runtime"
  version = "=v0.1.8"

[[constraint]]
  name = "github.com/operator-framework/operator-sdk"
  version = "=v0.5.0" #osdk_version_annotation

[[override]]
  name = "github.com/PuerkitoBio/urlesc"
  revision = "de5bf2ad457846296e2031421a34e2568e304e35"

[[override]]
  name = "github.com/alecthomas/template"
  revision = "a0175ee3bccc567396460bf5acd36800cb10c49c"

[[override]]
  name = "github.com/alecthomas/units"
  revision = "2efee857e7cfd4f3d0138cc3cbb1b4966962b93a"

[[override]]
  name = "github.com/beorn7/perks"
  revision = "3a771d992973f24aa725d07868b467d1ddfceafb"

[[override]]
  name = "github.com/docker/spdystream"
  revision = "449fdfce4d962303d702fec724ef0ad181c92528"

[[override]]
  name = "github.com/go-logr/logr"
  revision = "9fb12b3b21c5415d16ac18dc5cd42c1cfdd40c4e"

[[override]]
  name = "github.com/go-openapi/jsonpointer"
  version = "v0.16.0"

[[override]]
  name = "github.com/go-openapi/jsonreference"
  version = "v0.16.0"

[[override]]
  name = "github.com/go-openapi/spec"
  version = "v0.16.0"

[[override]]
  name = "github.com/go-openapi/swag"
  version = "v0.16.0"

[[override]]
  name = "github.com/golang/glog"
  revision = "44145f04b68cf362d9c4df2182967c2275eaefed"

[[override]]
  name = "github.com/golang/groupcache"
  revision = "c65c006176ff7ff98bb916961c7abbc6b0afc0aa"

[[override]]
  name = "github.com/google/btree"
  revision = "4030bb1f1f0c35b30ca7009e9ebd06849dd45306"

[[override]]
  name = "github.com/google/gofuzz"
  revision = "44d81051d367757e1c7c6a5a86423ece9afcf63c"

[[override]]
  name = "github.com/gregjones/httpcache"
  revision = "9cad4c3443a7200dd6400aef47183728de563a38"

[[override]]
  name = "github.com/json-iterator/go"
  version = "v1.1.3"

[[override]]
  name = "github.com/mailru/easyjson"
  revision = "60711f1a8329503b04e1c88535f419d0bb440bff"

[[override]]
  name = "github.com/mattbaird/jsonpatch"
  revision = "81af80346b1a01caae0cbc27fd3c1ba5b11e189f"

[[override]]
  name = "github.com/modern-go/reflect2"
  version = "1.0.0"

[[override]]
  name = "github.com/petar/GoLLRB"
  revision = "53be0d36a84c2a886ca057d34b6aa4468df9ccb4"

[[override]]
  name = "github.com/prometheus/client_golang"
  version = "0.9.2"

[[override]]
  name = "github.com/prometheus/client_model"
  revision = "fd36f4220a901265f90734c3183c5f0c91daa0b8"

[[override]]
  name = "github.com/prometheus/common"
  revision = "bf857faf208676b0294bd49959aa34c8d98163ed"

[[override]]
  name = "github.com/prometheus/procfs"
  revision = "6ed1f7e1041181781dd2826d3001075d011a80cc"

[[override]]
  name = "github.com/sirupsen/logrus"
  version = "0.11.5"

[[override]]
  name = "github.com/spf13/pflag"
  version = "v1.0.1"

[[override]]
  name = "google.golang.org/appengine"
  version = "v1.2.0"

[[override]]
  name = "gopkg.in/inf.v0"
  revision = "3887ee99ecf07df5b447e9b00d9c0b2adaa9f3e4"

[[override]]
  name = "gopkg.in/yaml.v2"
  version = "v2.2.1"

[[override]]
  name = "k8s.io/gengo"
  revision = "fd15ee9cc2f77baa4f31e59e6acbf21146455073"

[[override]]
  name = "k8s.io/kube-openapi"
  revision = "0317810137be915b9cf888946c6e115c1bfac693"

[prune]
  go-tests = true
  non-go = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    non-go = false
