apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
kind: ControllerManagerConfig
health:
  healthProbeBindAddress: :6789
metrics:
  bindAddress: 127.0.0.1:60000
webhook:
  port: 9443
leaderElection:
  leaderElect: true
  resourceName: e79b08a4.org.eclipse.che
