# permissions for end users to view chebackupserverconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chebackupserverconfiguration-viewer-role
rules:
- apiGroups:
  - org.eclipse.che
  resources:
  - chebackupserverconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - org.eclipse.che
  resources:
  - chebackupserverconfigurations/status
  verbs:
  - get
