# permissions for end users to edit chebackupserverconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chebackupserverconfiguration-editor-role
rules:
- apiGroups:
  - org.eclipse.che
  resources:
  - chebackupserverconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - org.eclipse.che
  resources:
  - chebackupserverconfigurations/status
  verbs:
  - get
