#
# Copyright (c) 2019-2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Red Hat, Inc. - initial API and implementation
#

# permissions for end users to view checlusterrestores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: checlusterrestore-viewer-role
rules:
- apiGroups:
  - org.eclipse.che
  resources:
  - checlusterrestores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - org.org.eclipse.che
  resources:
  - checlusterrestores/status
  verbs:
  - get
