# permissions for end users to edit checlusterrestores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: checlusterrestore-editor-role
rules:
- apiGroups:
  - org.eclipse.che
  resources:
  - checlusterrestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - org.eclipse.che
  resources:
  - checlusterrestores/status
  verbs:
  - get
