# permissions for end users to edit checlusterbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: checlusterbackup-editor-role
rules:
- apiGroups:
  - org.eclipse.che
  resources:
  - checlusterbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - org.eclipse.che
  resources:
  - checlusterbackups/status
  verbs:
  - get
