# permissions for end users to view checlusterbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: checlusterbackup-viewer-role
rules:
- apiGroups:
  - org.eclipse.che
  resources:
  - checlusterbackups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - org.eclipse.che
  resources:
  - checlusterbackups/status
  verbs:
  - get
