#
# Copyright (c) 2019-2025 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Red Hat, Inc. - initial API and implementation
#

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: eclipse-che-view
  labels:
    app.kubernetes.io/name: che
    app.kubernetes.io/instance: che
    app.kubernetes.io/component: che
    app.kubernetes.io/part-of: che.eclipse.org
rules:
  # CheCluster
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - org.eclipse.che
    resources:
      - checlusters
  # DevWorkspace
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - workspace.devfile.io
    resources:
      - devworkspaces
      - devworkspacetemplates
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - controller.devfile.io
    resources:
      - devworkspaceroutings
      - devworkspaceoperatorconfigs
  # Kubernetes Image Puller
  - apiGroups:
      - che.eclipse.org
    resources:
      - kubernetesimagepullers
    verbs:
      - get
      - list
      - watch
  # OLM
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - operators.coreos.com
    resources:
      - clusterserviceversions
      - catalogsources
      - installplans
      - operatorgroups
      - subscriptions
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - packages.operators.coreos.com
    resources:
      - packagemanifests
      - packagemanifests/icon
  # Viewing operators in OperatorHub
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - operator.openshift.io
    resources:
      - cloudcredentials
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - config.openshift.io
    resources:
      - infrastructures
      - authentications
  # Others
  - verbs:
      - get
      - list
    apiGroups:
      - ''
    resources:
      - namespaces
  - verbs:
      - get
      - list
    apiGroups:
      - project.openshift.io
    resources:
      - projects
  - apiGroups:
      - ''
    resources:
      - pods/log
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - configmaps
      - persistentvolumeclaims
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - template.openshift.io
    resources:
      - templates
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - serviceaccounts
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - events
    verbs:
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
      - clusterroles
      - clusterrolebindings
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    verbs:
      - get
      - list
      - watch