apiVersion: org.eclipse.che/v1
kind: CheClusterBackup
metadata:
  name: eclipse-che-backup
spec:
  # If true will setup REST backup server pod and add configuration to use it
  autoconfigureRestBackupServer: false
  # Set to true to start backup process
  triggerNow: false
  # Might be omitted if only one server configured
  serverType: 'sftp'
  # Usually only one server is needed
  servers:
    rest:
      hostname: rest-host.net
      repo: che
      repoPassword:
        password: password
    sftp:
      hostname: sftp-host.net
      username: user
      port: 2222
      sshKeySecretRef: backup-server-ssh-key-secret
      repo: che-backups
      repoPassword:
        passwordSecretRef: backups-password-secret
    awss3:
      awsAccessKeySecretRef: minio-credentials-secret
      hostname: minio.mydomain.net
      port: 9000
      protocol: http
      # Bucket should be pre-created
      repo: che-backups-bucket
      repoPassword:
        passwordSecretRef: backups-password-secret
