apiVersion: org.eclipse.che/v1
kind: CheClusterRestore
metadata:
  name: example-checlusterrestore
spec:
  deleteAfterRestore: false
  triggerNow: true
  servers:
    rest:
      hostname: rest-host.net
      repo: che
      repoPassword:
        password: password
  crOverrides:
    ingressDomain: che-eclipse-che.k8s.domain.net
