apiVersion: org.eclipse.che/v1
kind: CheBackupServerConfiguration
metadata:
  name: example-chebackupserverconfiguration
spec:
  # Contains backup server configuration.
  # Only one configuration is allowed.
  # Here different kinds are given as examples, but configuring several subsection will cause an error.
  rest:
    hostname: rest-host.net
    repositoryPath: che
    repositoryPasswordSecretRef: secret-name
  sftp:
    hostname: sftp-host.net
    username: user
    port: 2222
    sshKeySecretRef: backup-server-ssh-key-secret
    repositoryPath: che-backups
    repositoryPasswordSecretRef: secret-name
  awss3:
    awsAccessKeySecretRef: minio-credentials-secret
    hostname: minio.mydomain.net
    port: 9000
    protocol: http
    # Bucket should be pre-created
    repositoryPath: che-backups-bucket
    repositoryPasswordSecretRef: secret-name
