apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: che-operator
    app.kubernetes.io/instance: che
    app.kubernetes.io/name: che
    app.kubernetes.io/part-of: che.eclipse.org
  name: che-operator
  namespace: eclipse-che
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: che-operator
subjects:
- kind: ServiceAccount
  name: che-operator
