apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: eclipse-che/che-operator-serving-cert
  labels:
    app.kubernetes.io/component: che-operator
    app.kubernetes.io/instance: che
    app.kubernetes.io/name: che
    app.kubernetes.io/part-of: che.eclipse.org
  name: org.eclipse.che
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: che-operator-service
      namespace: eclipse-che
      path: /mutate-org-eclipse-che-v2-checluster
  failurePolicy: Fail
  name: mchecluster.kb.io
  rules:
  - apiGroups:
    - org.eclipse.che
    apiVersions:
    - v2
    operations:
    - CREATE
    - UPDATE
    resources:
    - checlusters
  sideEffects: None
