apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: che-operator-proxy
  labels:
    app.kubernetes.io/name: che
    app.kubernetes.io/instance: che
    app.kubernetes.io/component: che-operator
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
