// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/controller/che/initial-htpasswd-provider.go

// Package mock_che is a generated GoMock package.
package mock_util

import (
	gomock "github.com/golang/mock/gomock"
	v1 "github.com/openshift/api/config/v1"
	reflect "reflect"
)

// MockInitialUserHandler is a mock of InitialUserHandler interface
type MockInitialUserHandler struct {
	ctrl     *gomock.Controller
	recorder *MockInitialUserHandlerMockRecorder
}

// MockInitialUserHandlerMockRecorder is the mock recorder for MockInitialUserHandler
type MockInitialUserHandlerMockRecorder struct {
	mock *MockInitialUserHandler
}

// NewMockInitialUserHandler creates a new mock instance
func NewMockInitialUserHandler(ctrl *gomock.Controller) *MockInitialUserHandler {
	mock := &MockInitialUserHandler{ctrl: ctrl}
	mock.recorder = &MockInitialUserHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockInitialUserHandler) EXPECT() *MockInitialUserHandlerMockRecorder {
	return m.recorder
}

// CreateOauthInitialUser mocks base method
func (m *MockInitialUserHandler) CreateOauthInitialUser(crNamespace string, openshiftOAuth *v1.OAuth) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOauthInitialUser", crNamespace, openshiftOAuth)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOauthInitialUser indicates an expected call of CreateOauthInitialUser
func (mr *MockInitialUserHandlerMockRecorder) CreateOauthInitialUser(crNamespace, openshiftOAuth interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOauthInitialUser", reflect.TypeOf((*MockInitialUserHandler)(nil).CreateOauthInitialUser), crNamespace, openshiftOAuth)
}

// DeleteOauthInitialUser mocks base method
func (m *MockInitialUserHandler) DeleteOauthInitialUser(crNamespace string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOauthInitialUser", crNamespace)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOauthInitialUser indicates an expected call of DeleteOauthInitialUser
func (mr *MockInitialUserHandlerMockRecorder) DeleteOauthInitialUser(crNamespace interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOauthInitialUser", reflect.TypeOf((*MockInitialUserHandler)(nil).DeleteOauthInitialUser), crNamespace)
}
