kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: che-operator
rules:
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
    verbs:
      - list
      - create
      - watch
      - update
