FROM quay.io/operator-framework/upstream-registry-builder as builder

COPY deploy manifests/eclipse-che-preview-openshift
RUN ./bin/linux-amd64-initializer -o ./bundles.db

FROM scratch
COPY --from=builder /build/bundles.db /bundles.db
COPY --from=builder /build/bin/linux-amd64-registry-server /registry-server
COPY --from=builder /bin/grpc_health_probe /bin/grpc_health_probe
EXPOSE 50051
ENTRYPOINT ["/registry-server"]
CMD ["--database", "bundles.db"]
