#
#  Copyright (c) 2012-2020 Red Hat, Inc.
#    This program and the accompanying materials are made
#    available under the terms of the Eclipse Public License 2.0
#    which is available at https://www.eclipse.org/legal/epl-2.0/
#
#  SPDX-License-Identifier: EPL-2.0
#
#  Contributors:
#    Red Hat, Inc. - initial API and implementation
#

name: Minishift
on: pull_request
jobs:
  minishift-update:
    name: Testing stable versions updates
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Provision Minishift cluster
      run: |
        brew cask install minishift
        export MINISHIFT_GITHUB_API_TOKEN=${{ secrets.GITHUB_TOKEN }}
        minishift start --memory=5500 --vm-driver=virtualbox
    - name: Install chectl
      run: bash <(curl -sL  https://www.eclipse.org/che/chectl/) --channel=stable
    - name: Install jq
      run: sudo pip install yq
    - name: Replace Minishift default certificates
      run: /bin/bash .github/bin/minishift/certs.sh
    - name: Update minishift deprecated certificates and run e2e
      run: |
        eval $(minishift oc-env)
        /bin/bash .github/bin/minishift/test-update-operator.sh
    # Run this step even the previous step fail
    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: minishift-updates-artifacts
        path: /tmp/artifacts-che
