#
# Copyright (c) 2019-2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Red Hat, Inc. - initial API and implementation
#

name: Minishift
on:
  pull_request:
    branches:
     - 7.*
jobs:
  minishift-update:
    name: Testing stable versions updates
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Provision Minishift cluster
      run: |
        brew install minishift
        export MINISHIFT_GITHUB_API_TOKEN=${{ secrets.GITHUB_TOKEN }}
        minishift start --memory=5500 --vm-driver=virtualbox --registry-mirror=https://quay.io
    - name: Install chectl
      run: bash <(curl -sL  https://www.eclipse.org/che/chectl/) --channel=next
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install yq and pysemver
      run: |
        pip3 install operator-courier==2.1.7
        sudo pip install pysemver;
        sudo pip install yq
        echo "[INFO] pysemver version:"
        pysemver --version;
        echo "[INFO] yq version:"
        yq --version;
    - name: Replace Minishift default certificates
      run: /bin/bash .github/bin/minishift/certs.sh
    - name: Update minishift deprecated certificates and run e2e
      run: |
        eval $(minishift oc-env)
        /bin/bash .github/bin/minishift/test-stable-operator-update.sh
      env:
        "GITHUB_TOKEN": "${{ secrets.GITHUB_TOKEN }}"
    # Run this step even the previous step fail
    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: minishift-updates-artifacts
        path: /tmp/artifacts-che
