#
#  Copyright (c) 2012-2020 Red Hat, Inc.
#    This program and the accompanying materials are made
#    available under the terms of the Eclipse Public License 2.0
#    which is available at https://www.eclipse.org/legal/epl-2.0/
#
#  SPDX-License-Identifier: EPL-2.0
#
#  Contributors:
#    Red Hat, Inc. - initial API and implementation
#
name: Minikube
on: pull_request
jobs:
  minikube-gateway:
    name: Testing latest changes (single-host/gateway)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Provision Minikube cluster
      run:  /bin/bash .ci/start-minikube.sh
    - name: Install chectl
      run: bash <(curl -sL https://www.eclipse.org/che/chectl/) --channel=next
    - name: Run tests
      run: /bin/bash .github/bin/minikube/single-host-gateway-test.sh
    # Run this step even the previous step fail to upload artifacts to GH
    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: minikube-single-host-gateway-artifacts
        path: /tmp/artifacts-che
  minikube-native:
    name: Testing latest changes (single-host/native)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Provision Minikube cluster
      run:  /bin/bash .ci/start-minikube.sh
    - name: Install chectl
      run: bash <(curl -sL  https://www.eclipse.org/che/chectl/) --channel=next
    - name: Run tests
      run: /bin/bash .github/bin/minikube/single-host-native-test.sh
    # Run this step even the previous step fail to upload artifacts to GH
    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: minikube-single-host-native-artifacts
        path: /tmp/artifacts-che
