#
# Copyright (c) 2019-2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Red Hat, Inc. - initial API and implementation
#

name: Build next images

on:
  # manual trigger if required
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason to trigger a build'
        required: false
  schedule:
    - cron:  '0 0 * * *'
jobs:
  build-images:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to quay.io
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}
        registry: quay.io
    - name: Build and push images to quay.io
      uses: docker/build-push-action@v2
      with:
        file: Dockerfile
        platforms: linux/amd64,linux/ppc64le
        push: true
        tags: quay.io/eclipse/che-operator:next
