#
# Copyright (c) 2019-2026 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Red Hat, Inc. - initial API and implementation
#

name: PR Image Build
on: pull_request
permissions:
  contents: read
  pull-requests: write
jobs:
  image-build-amd64:
    runs-on: ubuntu-24.04
    if: ${{ github.event.pull_request.user.login != 'dependabot[bot]' }}
    env:
      IMAGE_VERSION: pr-${{ github.event.pull_request.number }}-amd64
      ORGANIZATION: quay.io/eclipse
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to quay.io
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}
    - name: Build and push amd64 image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        provenance: false
        tags: ${{ env.ORGANIZATION }}/che-operator:${{ env.IMAGE_VERSION }}
    - name: Comment with image name
      uses: actions/github-script@v7
      with:
        script: |
          const { issue: { number: issue_number }, repo: { owner, repo } } = context;
          const operatorImage = "${{ env.ORGANIZATION }}/che-operator:${{ env.IMAGE_VERSION }}";
          github.rest.issues.createComment({ issue_number, owner, repo, body: `New operator image available: ${operatorImage}` });
  image-build-arm64:
    runs-on: ubuntu-24.04-arm
    if: ${{ github.event.pull_request.base.ref == 'main' && github.event.pull_request.user.login != 'dependabot[bot]' }}
    env:
      IMAGE_VERSION: pr-${{ github.event.pull_request.number }}-arm64
      ORGANIZATION: quay.io/eclipse
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to quay.io
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}
    - name: Build and push arm64 image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/arm64
        push: true
        provenance: false
        tags: ${{ env.ORGANIZATION }}/che-operator:${{ env.IMAGE_VERSION }}
    - name: Comment with image name
      uses: actions/github-script@v7
      with:
        script: |
          const { issue: { number: issue_number }, repo: { owner, repo } } = context;
          const operatorImage = "${{ env.ORGANIZATION }}/che-operator:${{ env.IMAGE_VERSION }}";
          github.rest.issues.createComment({ issue_number, owner, repo, body: `New operator image available: ${operatorImage}` });
