#
#  Copyright (c) 2012-2020 Red Hat, Inc.
#    This program and the accompanying materials are made
#    available under the terms of the Eclipse Public License 2.0
#    which is available at https://www.eclipse.org/legal/epl-2.0/
#
#  SPDX-License-Identifier: EPL-2.0
#
#  Contributors:
#    Red Hat, Inc. - initial API and implementation
#
name: Push catalog and bundle images.
on:
  schedule:
    - cron:  '0 21 * * *'
      branches:
        - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        path: go/src/github.com/eclipse/${{ github.repository }}
        fetch-depth: 0

    - name: Prepare new nightly Olm bundle
      run: >-
        export GOPATH="${GITHUB_WORKSPACE}/go" &&
        echo "GOPATH: ${GOPATH}" &&
        export GITHUB_WORKSPACE="${GOPATH}/src/github.com/eclipse/${{ github.repository }}" &&
        cd ${GITHUB_WORKSPACE} && "${GITHUB_WORKSPACE}/.github/action_scripts/provideNewNightlyBundle.sh"

    - name: Commit new nightly Olm bundle
      uses: EndBug/add-and-commit@v5
      with:
        add: "*.yaml"
        cwd: go/src/github.com/eclipse/${{ github.repository }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker login
      uses: azure/docker-login@v1
      with:
        login-server: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: Build catalog source and opm bundle images
      run: >-
        export GITHUB_WORKSPACE=${GITHUB_WORKSPACE}/go/src/github.com/eclipse/${{ github.repository }} &&
        ${GITHUB_WORKSPACE}/.github/action_scripts/build_olm_bundle_images.sh
