#
# Copyright (c) 2019-2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Red Hat, Inc. - initial API and implementation
#

name: Release next catalog
on:
  # manual trigger if required
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason to trigger a build'
        required: false
  push:
    branches:
      - main
jobs:
  release-next-catalog:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Install yq
      run: sudo pip install yq
    - name: Docker login
      uses: azure/docker-login@v1
      with:
        login-server: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}
    - name: Release next catalog
      run: |
        git config --global user.name "Anatolii Bazko"
        git config --global user.email "abazko@redhat.com"
        export GITHUB_TOKEN=${{ secrets.CHE_BOT_GITHUB_TOKEN }}

        ${GITHUB_WORKSPACE}/build/scripts/olm/release-catalog.sh --channel 'next' --catalog-image quay.io/eclipse/eclipse-che-olm-catalog:next
        
        git add -A olm-catalog/next
        git commit -m "chore(catalog): release "
        git push origin main
